name: 'Terraform Route53 DNS Record'
description: 'Create or update a Route 53 record for a subdomain using Terraform'

inputs:
  project-name:
    description: 'Project name used for tagging resources'
    required: true

  root-domain:
    description: 'Root domain (e.g., example.com)'
    required: true

  subdomain:
    description: 'Subdomain to create (e.g., www, app)'
    required: true

  target-domain:
    description: 'Value for the DNS record (e.g., CloudFront domain or S3 website endpoint)'
    required: true

  target-record-type:
    description: 'DNS record type (e.g., A or CNAME)'
    required: false
    default: 'CNAME'

  terraform-dir:
    description: 'Path to the Terraform module directory'
    required: true

  aws-region:
    description: 'AWS region to use'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Terraform Init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Terraform Plan
      run: |
        terraform plan \
          -var "aws_region=${{ inputs.aws-region }}" \
          -var "root_domain=${{ inputs.root-domain }}" \
          -var "subdomain=${{ inputs.subdomain }}" \
          -var "target_domain=${{ inputs.target-domain }}" \
          -var "target_record_type=${{ inputs.target-record-type }}" \
          -out=tfplan
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
