name: Deploy Serverless App
description: Deploy a Node.js app to AWS using the Serverless Framework.
author: Woragis
inputs:
  serverless_token:
    description: Serverless Dashboard access token
    required: true
  org:
    description: Serverless organization name
    required: true
  app:
    description: Serverless app name
    required: true
  node_version:
    description: Node.js version
    default: '18'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 📥 Checkout
      uses: actions/checkout@v3

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: 📦 Install Serverless
      run: npm install -g serverless
      shell: bash

    - name: 🔐 Authenticate Serverless
      run: |
        mkdir -p ~/.serverless
        echo "{\"userId\":\"cli\",\"frameworkId\":\"cli\",\"dashboard\":true,\"token\":\"${{ inputs.serverless_token }}\"}" > ~/.serverless/auth.json
      shell: bash

    - name: 🚀 Deploy
      run: serverless deploy --org ${{ inputs.org }} --app ${{ inputs.app }}
      shell: bash
